### ISSUE TITLE
No contigs for extraction specified

### ISSUE THREAD

**Issue by kvaldez** [DiltheyLab/HLA-LA#90]
Hello!  I created an extraction file for my data based on the documentation, however I'm running into this error:

No contigs for extraction specified in /opt/conda/envs/hla-la/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences/hla-la_hg19_Compass.txt? at /opt/conda/envs/hla-la/bin/HLA-LA.pl line 391.

I attached my file here, can you suggest a solution?
[hla-la_hg19_Compass.txt](https://github.com/DiltheyLab/HLA-LA/files/11031340/hla-la_hg19_Compass.txt)

Thanks,
Kristin

**Comment by Zoeyoungxy** [comment]
Hello! I met the same question. Have you solved the problem? 
The error message:
Using /home/anaconda3/envs/hlala/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences/reference_extraction_UNIX.txt as reference file.
No contigs for extraction specified in /home/anaconda3/envs/hlala/opt/hla-la/src/../graphs/PRG_MHC_GRCh38_withIMGT/knownReferences/reference_extraction_UNIX.txt? at /home/anaconda3/envs/hlala/bin/HLA-LA.pl line 391.

The samtools idxstats file and reference_extraction file:
[reference_extraction_UNIX.txt](https://github.com/DiltheyLab/HLA-LA/files/11319727/reference_extraction_UNIX.txt)
[sample.idxstats.txt](https://github.com/DiltheyLab/HLA-LA/files/11319729/sample.idxstats.txt)

Any suggestions will be highly appreciated. 

Thanks,
-Zoey

**Comment by kvaldez** [comment]
Hi Zoey! No unfortunately I haven't resolved the issue either.

Kristin

**Comment by AlexanderDilthey** [comment]
Hi @kvaldez and @Zoeyoungxy,

The issue is that the file does not specify any genomic locations as targets for the extraction process - i.e. there are no values / only 0 in the columns `ExtractCompleteContig`, `PartialExtraction_Start`, and `PartialExtraction_Stop`. 

Check out e.g. https://github.com/DiltheyLab/HLA-LA/blob/master/additionalReferences/PRG_MHC_GRCh38_withIMGT/G1000_Ymasked.txt for an example - the general strategy should be to mark the complete MHC for extraction, plus any alternative MHC or HLA allele contigs.

Best wishes,

Alex
